### ISSUE TITLE
Rename language code from `ita` to `it`

### ISSUE THREAD

**Issue by iPurpl3x** [flarum-lang/italian#2]
I realized that this new language pack (compared to the one that existed before flarum 1.0) is now using `ita` as language code and not `it` as previously! 

Why did that change happen? Could it be reversed?

On my side this breaks a lot of things like the [fof/discussion-language fork](https://github.com/glowingblue/discussion-language/tree/gb-stable1-0) of Glowing Blue... (What happens is that it tries to view discussions with the `ita` language code. And there is none, because fof/discussion-language saves them with the `it` code.

**Comment by justoverclockl** [comment]
https://github.com/flarum-lang/italian/releases/tag/1.0.13

done
